def listDefault():
	return """_admin
	_admin/operations.aspx
	_app_bin
	_catalogs/masterpage/forms/allitems.aspx
	_catalogs/wp/forms/allitems.aspx
	_catalogs/wt/forms/common.aspx
	_catalogs/lt/forms/allitems.aspx
	_controltemplates
	_layouts
	_layouts/accessdenied.aspx
	_layouts/aclinv.aspx
	_layouts/addcontentsource.aspx
	_layouts/addcontenttypetolist.aspx
	_layouts/addfieldfromtemplate.aspx
	_layouts/addfiletype.aspx
	_layouts/addnavigationlinkdialog.aspx
	_layouts/addrole.aspx
	_layouts/addservernamemappings.aspx
	_layouts/addwrkfl.aspx
	_layouts/adminrecyclebin.aspx
	_layouts/advsetng.aspx
	_layouts/approve.aspx
	_layouts/areacachesettings.aspx
	_layouts/areanavigationsettings.aspx
	_layouts/areatemplatesettings.aspx
	_layouts/areawelcomepage.aspx
	_layouts/aspxform.aspx
	_layouts/assetedithyperlink.aspx
	_layouts/assetimagepicker.aspx
	_layouts/assetportalbrowser.aspx
	_layouts/assetuploader.aspx
	_layouts/associatedgroups.aspx
	_layouts/assocwrkfl.aspx
	_layouts/audience_defruleedit.aspx
	_layouts/audience_edit.aspx
	_layouts/audience_list.aspx
	_layouts/audience_main.aspx
	_layouts/audience_memberlist.aspx
	_layouts/audience_sched.aspx
	_layouts/audience_view.aspx
	_layouts/auditsettings.aspx
	_layouts/authenticate.aspx
	_layouts/avreport.aspx
	_layouts/backlinks.aspx
	_layouts/barcodeimagefromitem.aspx
	_layouts/bdcadminui/addbdcaction.aspx
	_layouts/bdcadminui/addbdcapplication.aspx  
	_layouts/bdcadminui/bdcapplications.aspx    
	_layouts/bdcadminui/bdcentities.aspx           
	_layouts/bdcadminui/editbdcaction.aspx         
	_layouts/bdcadminui/exportbdcapplication.aspx  
	_layouts/bdcadminui/managepermissions.aspx
	_layouts/bdcadminui/viewbdcapplication.aspx
	_layouts/bdcadminui/viewbdcentity.aspx
	_layouts/bestbet.aspx
	_layouts/bpcf.aspx
	_layouts/bulkwrktaskhandler.aspx
	_layouts/bulkwrktaskip.aspx
	_layouts/businessdatasynchronizer.aspx
	_layouts/category.aspx
	_layouts/changecontenttypeoptionalsettings.aspx
	_layouts/changecontenttypeorder.aspx
	_layouts/changefieldorder.aspx
	_layouts/changesitemasterpage.aspx
	_layouts/checkin.aspx
	_layouts/cmsslwpaddeditgroup.aspx
	_layouts/cmsslwpaddeditlink.aspx
	_layouts/cmsslwpeditview.aspx
	_layouts/cmsslwpsortlinks.aspx
	_layouts/confirmation.aspx
	_layouts/conngps.aspx
	_layouts/containerpicker.aspx
	_layouts/contentaccessaccount.aspx
	_layouts/contenttypeconvertersettings.aspx
	_layouts/convertersettings.aspx
	_layouts/copy.aspx
	_layouts/copyresults.aspx
	_layouts/copyrole.aspx
	_layouts/copyutil.aspx
	_layouts/crawledproperty.aspx
	_layouts/create.aspx
	_layouts/createadaccount.aspx
	_layouts/createpage.aspx
	_layouts/createwebpage.aspx
	_layouts/createworkbook.aspx
	_layouts/createws.aspx
	_layouts/cstwrkflip.aspx
	_layouts/ctdmsettings.aspx
	_layouts/ctypedit.aspx
	_layouts/ctypenew.aspx
	_layouts/customizereport.aspx
	_layouts/deactivatefeature.aspx
	_layouts/deletemu.aspx
	_layouts/deleteweb.aspx
	_layouts/discbar.aspx
	_layouts/dladvopt.aspx
	_layouts/dmplaceholder.aspx
	_layouts/doctrans.aspx
	_layouts/download.aspx
	_layouts/dws.aspx
	_layouts/dynamicimageprovider.aspx
	_layouts/editcontentsource.aspx
	_layouts/editcopyinformation.aspx
	_layouts/editcrawlrule.aspx
	_layouts/editdsserver.aspx
	_layouts/editgrp.aspx
	_layouts/editnav.aspx
	_layouts/editpolicy.aspx
	_layouts/editprms.aspx
	_layouts/editprofile.aspx
	_layouts/editproperty.aspx
	_layouts/editpropertynames.aspx
	_layouts/editpropertynames2.aspx
	_layouts/editrelevancesettings.aspx
	_layouts/editrole.aspx
	_layouts/editschedule.aspx
	_layouts/editsection.aspx
	_layouts/editview.aspx
	_layouts/emaildetails.aspx
	_layouts/emailsettings.aspx
	_layouts/enablealerts.aspx
	_layouts/enhancedsearch.aspx
	_layouts/error.aspx
	_layouts/ewrcustomfilter.aspx
	_layouts/ewrfilter.aspx
	_layouts/ewrfind.aspx
	_layouts/ewrpredialog.aspx
	_layouts/ewrtop10.aspx
	_layouts/excelcellpicker.aspx
	_layouts/excelprofilepage.aspx
	_layouts/excelrenderer.aspx
	_layouts/excelserversafedataprovider.aspx
	_layouts/excelserversafedataproviders.aspx
	_layouts/excelserversettings.aspx
	_layouts/excelservertrusteddcl.aspx
	_layouts/excelservertrusteddcls.aspx
	_layouts/excelservertrustedlocation.aspx
	_layouts/excelservertrustedlocations.aspx
	_layouts/excelserveruserdefinedfunction.aspx
	_layouts/excelserveruserdefinedfunctions.aspx
	_layouts/exemptpolicy.aspx
	_layouts/exportpolicy.aspx
	_layouts/feed.aspx
	_layouts/filter.aspx
	_layouts/filtervaluespickerdialog.aspx
	_layouts/fldedit.aspx
	_layouts/fldeditex.aspx
	_layouts/fldnew.aspx
	_layouts/fldnewex.aspx
	_layouts/fldpick.aspx
	_layouts/folders.aspx
	_layouts/formedt.aspx
	_layouts/formresource.aspx
	_layouts/formserver.aspx
	_layouts/formserverattachments.aspx
	_layouts/formserverdetector.aspx
	_layouts/gear.aspx
	_layouts/genericpicker.aspx
	_layouts/getdataconnectionfile.aspx
	_layouts/getssploginfo.aspx
	_layouts/getsspscopes.aspx
	_layouts/getsspstatus.aspx
	_layouts/groups.aspx
	_layouts/help.aspx
	_layouts/helpcontent.aspx
	_layouts/helpsearch.aspx
	_layouts/hold.aspx
	_layouts/holdreport.aspx
	_layouts/htmledit.aspx
	_layouts/htmltranslate.aspx
	_layouts/htmltrredir.aspx
	_layouts/htmltrverify.aspx
	_layouts/iframe.aspx
	_layouts/images/
	_layouts/importpolicy.aspx
	_layouts/indxcol.aspx
	_layouts/infopage.aspx
	_layouts/iniwrkflip.aspx
	_layouts/irm.aspx
	_layouts/irmrept.aspx
	_layouts/itemrwfassoc.aspx
	_layouts/iviewhost.aspx
	_layouts/keyword.aspx
	_layouts/labelimage.aspx
	_layouts/linkschecker.aspx
	_layouts/linkscheckerwiz.aspx
	_layouts/listcontentsources.aspx
	_layouts/listedit.aspx
	_layouts/listenabletargeting.aspx
	_layouts/listfeed.aspx
	_layouts/listgeneralsettings.aspx
	_layouts/listkeywords.aspx
	_layouts/listservernamemappings.aspx
	_layouts/listsyndication.aspx
	_layouts/login.aspx
	_layouts/logsummary.aspx
	_layouts/logviewer.aspx
	_layouts/longrunningoperationprogress.aspx
	_layouts/lroperationstatus.aspx
	_layouts/lstsetng.aspx
	_layouts/managecheckedoutfiles.aspx
	_layouts/managecontenttype.aspx
	_layouts/managecontenttypefield.aspx
	_layouts/managecopies.aspx
	_layouts/managecrawlrules.aspx
	_layouts/managedproperty.aspx
	_layouts/managefeatures.aspx
	_layouts/managefeatures.aspx?scope=site
	_layouts/managefiletypes.aspx
	_layouts/manageitemscheduling.aspx
	_layouts/manageprivacypolicy.aspx
	_layouts/manageservicepermissions.aspx
	_layouts/matchingrule.aspx
	_layouts/mcontent.aspx
	_layouts/metaweblog.aspx
	_layouts/mgrdsserver.aspx
	_layouts/mgrproperty.aspx
	_layouts/mngctype.aspx
	_layouts/mngdisc.aspx
	_layouts/mngfield.aspx
	_layouts/mngsiteadmin.aspx
	_layouts/mngsubwebs.aspx
	_layouts/mngsubwebs.aspx?view=sites
	_layouts/mobile/bloghome.aspx          
	_layouts/mobile/default.aspx           
	_layouts/mobile/delete.aspx            
	_layouts/mobile/dispform.aspx  
	_layouts/mobile/disppost.aspx  
	_layouts/mobile/editform.aspx  
	_layouts/mobile/mblerror.aspx  
	_layouts/mobile/mbllists.aspx    
	_layouts/mobile/mbllogin.aspx    
	_layouts/mobile/mbllogout.aspx   
	_layouts/mobile/mobileformserver.aspx  
	_layouts/mobile/newcomment.aspx  
	_layouts/mobile/newform.aspx
	_layouts/mobile/newpost.aspx
	_layouts/mobile/view.aspx
	_layouts/mobile/viewcomment.aspx
	_layouts/modwrkflip.aspx
	_layouts/mtgredir.aspx
	_layouts/mycontactlinks.aspx
	_layouts/myinfo.aspx
	_layouts/mymemberships.aspx
	_layouts/mypage.aspx
	_layouts/myquicklinks.aspx
	_layouts/mysite.aspx
	_layouts/mysiteheader.aspx
	_layouts/mysubs.aspx
	_layouts/mytasks.aspx
	_layouts/navoptions.aspx
	_layouts/new.aspx
	_layouts/newdwp.aspx
	_layouts/newgrp.aspx
	_layouts/newlink.aspx
	_layouts/newmws.aspx
	_layouts/newnav.aspx
	_layouts/newpagelayout.aspx
	_layouts/newsbweb.aspx
	_layouts/newtranslationmanagement.aspx
	_layouts/newvariationsite.aspx
	_layouts/nocrawlsettings.aspx
	_layouts/objectcachesettings.aspx
	_layouts/officialfilesetup.aspx
	_layouts/officialfilesuccess.aspx
	_layouts/osssearchresults.aspx
	_layouts/pagesettings.aspx
	_layouts/pageversioninfo.aspx
	_layouts/password.aspx
	_layouts/permsetup.aspx
	_layouts/personalsites.aspx
	_layouts/picker.aspx
	_layouts/pickerresult.aspx
	_layouts/pickertreeview.aspx
	_layouts/policy.aspx
	_layouts/policyconfig.aspx
	_layouts/policycts.aspx
	_layouts/policylist.aspx
	_layouts/portal.aspx
	_layouts/portalview.aspx
	_layouts/postback.formserver.aspx
	_layouts/print.formserver.aspx
	_layouts/printloader.formserver.aspx
	_layouts/prjsetng.aspx
	_layouts/profadminedit.aspx
	_layouts/profileredirect.aspx
	_layouts/profmain.aspx
	_layouts/profmngr.aspx
	_layouts/profnew.aspx
	_layouts/proxy.aspx
	_layouts/publishback.aspx
	_layouts/qlreord.aspx
	_layouts/qstedit.aspx
	_layouts/qstnew.aspx
	_layouts/quicklinks.aspx
	_layouts/quicklinksdialog.aspx
	_layouts/quicklinksdialog2.aspx
	_layouts/quicklinksdialogform.aspx
	_layouts/quiklnch.aspx
	_layouts/rcxform.aspx
	_layouts/recyclebin.aspx
	_layouts/redirect.aspx
	_layouts/redirectpage.aspx
	_layouts/redirectpage.aspx?target={sitecollectionurl}_catalogs/masterpage
	_layouts/reghost.aspx
	_layouts/regionalsetng.aspx
	_layouts/releasehold.aspx
	_layouts/rellinksscopesettings.aspx
	_layouts/remwrkfl.aspx
	_layouts/renderudc.aspx
	_layouts/reorder.aspx
	_layouts/reporting.aspx
	_layouts/reqacc.aspx
	_layouts/reqfeatures.aspx
	_layouts/reqgroup.aspx
	_layouts/reqgroupconfirm.aspx
	_layouts/resolverecipient.aspx
	_layouts/reusabletextpicker.aspx
	_layouts/rfcxform.aspx
	_layouts/rfpxform.aspx
	_layouts/role.aspx
	_layouts/rssxslt.aspx
	_layouts/rte2ecell.aspx
	_layouts/rte2erowcolsize.aspx
	_layouts/rte2etable.aspx
	_layouts/rte2pueditor.aspx
	_layouts/rtedialog.aspx
	_layouts/runreport.aspx
	_layouts/savetmpl.aspx
	_layouts/schema.aspx
	_layouts/scope.aspx
	_layouts/scopedisplaygroup.aspx
	_layouts/scsignup.aspx
	_layouts/searchandaddtohold.aspx
	_layouts/searchreset.aspx
	_layouts/searchresultremoval.aspx
	_layouts/searchresults.aspx
	_layouts/searchsspsettings.aspx
	_layouts/selectcrawledproperty.aspx
	_layouts/selectmanagedproperty.aspx
	_layouts/selectpicture.aspx
	_layouts/selectpicture2.aspx
	_layouts/selectuser.aspx
	_layouts/sendtoofficialfile.aspx
	_layouts/setanon.aspx
	_layouts/setimport.aspx
	_layouts/setrqacc.aspx
	_layouts/settings.aspx
	_layouts/signature.formserver.aspx
	_layouts/signaturedetails.formserver.aspx
	_layouts/signaturedetailsloader.formserver.aspx
	_layouts/signaturedetailspngloader.formserver.aspx
	_layouts/signatureeula.formserver.aspx
	_layouts/signout.aspx
	_layouts/sitecachesettings.aspx
	_layouts/sitedirectorysettings.aspx
	_layouts/sitemanager.aspx
	_layouts/sitemanager.aspx?lro=all
	_layouts/siterss.aspx
	_layouts/sitesubs.aspx
	_layouts/sledit.aspx
	_layouts/slnew.aspx
	_layouts/smtcommentsdialog.aspx
	_layouts/spcf.aspx
	_layouts/spcontnt.aspx
	_layouts/spellchecker.aspx
	_layouts/spnewdashboard.aspx
	_layouts/spsredirect.aspx
	_layouts/spusageconfig.aspx
	_layouts/spusagesite.aspx
	_layouts/spusagesiteclickthroughs.aspx
	_layouts/spusagesitehomepage.aspx
	_layouts/spusagesitereferrers.aspx
	_layouts/spusagesitesearchqueries.aspx
	_layouts/spusagesitesearchresults.aspx
	_layouts/spusagesitetoppages.aspx
	_layouts/spusagesiteusers.aspx
	_layouts/spusagesspsearchqueries.aspx
	_layouts/spusagesspsearchresults.aspx
	_layouts/spusageweb.aspx
	_layouts/spusagewebclickthroughs.aspx
	_layouts/spusagewebhomepage.aspx
	_layouts/spusagewebreferrers.aspx
	_layouts/spusagewebtoppages.aspx
	_layouts/spusagewebusers.aspx
	_layouts/srchrss.aspx
	_layouts/srchvis.aspx
	_layouts/ssologon.aspx
	_layouts/storman.aspx
	_layouts/subchoos.aspx
	_layouts/subedit.aspx
	_layouts/submitrepair.aspx
	_layouts/subnew.aspx
	_layouts/success.aspx
	_layouts/survedit.aspx
	_layouts/templatepick.aspx
	_layouts/themeweb.aspx
	_layouts/tnreord.aspx
	_layouts/toolpane.aspx
	_layouts/topnav.aspx
	_layouts/translatablesettings.aspx
	_layouts/unapprovedresources.aspx
	_layouts/updatecopies.aspx
	_layouts/updateschedule.aspx
	_layouts/upload.aspx
	_layouts/usage.aspx
	_layouts/usagedetails.aspx
	_layouts/useconfirmation.aspx
	_layouts/user.aspx
	_layouts/variationexport.aspx
	_layouts/variationlabel.aspx
	_layouts/variationlabels.aspx
	_layouts/variationlogs.aspx
	_layouts/variations/variationimport.aspx
	_layouts/variationsettings.aspx
	_layouts/versiondiff.aspx
	_layouts/versions.aspx
	_layouts/viewedit.aspx
	_layouts/viewgrouppermissions.aspx
	_layouts/viewlsts.aspx
	_layouts/viewnew.aspx
	_layouts/viewscopes.aspx
	_layouts/viewscopesettings.aspx
	_layouts/viewtype.aspx
	_layouts/vsubwebs.aspx
	_layouts/webdeleted.aspx
	_layouts/webpartgallerypickerpage.aspx
	_layouts/workflow.aspx
	_layouts/workspce.aspx
	_layouts/wpeula.aspx
	_layouts/wrkmng.aspx
	_layouts/wrksetng.aspx
	_layouts/wrkstat.aspx
	_layouts/wrktaskip.aspx
	_layouts/wsrpmarkupproxy.aspx
	_layouts/xlatewfassoc.aspx
	_layouts/xlviewer.aspx
	_layouts/zoombldr.aspx
	_vti_adm
	_vti_adm/admin.asmx
	_vti_aut
	_vti_bin
	_vti_bin/_vti_adm/admin.dll
	_vti_bin/_vti_adm/fpadmdll.dll
	_vti_bin/_vti_aut/author.dll
	_vti_bin/admin.asmx
	_vti_bin/alerts.asmx
	_vti_bin/alertsdisco.aspx
	_vti_bin/alertswsdl.aspx
	_vti_bin/areaservice.asmx
	_vti_bin/areaservicedisco.aspx
	_vti_bin/areaservicewsdl.aspx
	_vti_bin/authentication.asmx
	_vti_bin/bdcfieldsresolver.asmx
	_vti_bin/businessdatacatalog.asmx
	_vti_bin/contentareatoolboxservice.asmx
	_vti_bin/copy.asmx
	_vti_bin/dspsts.asmx
	_vti_bin/dspstsdisco.aspx
	_vti_bin/dspstswsdl.aspx
	_vti_bin/dws.asmx
	_vti_bin/dwsdisco.aspx
	_vti_bin/dwswsdl.aspx
	_vti_bin/excelservice.asmx
	_vti_bin/exportwp.aspx
	_vti_bin/expurlwp.aspx
	_vti_bin/forms.asmx
	_vti_bin/formsdisco.aspx
	_vti_bin/formsserviceproxy.asmx
	_vti_bin/formsservices.asmx
	_vti_bin/formswsdl.aspx
	_vti_bin/global.asax
	_vti_bin/imaging.asmx
	_vti_bin/imagingdisco.aspx
	_vti_bin/imagingwsdl.aspx
	_vti_bin/lists.asmx
	_vti_bin/listsdisco.aspx
	_vti_bin/listswsdl.aspx
	_vti_bin/meetings.asmx
	_vti_bin/meetingsdisco.aspx
	_vti_bin/meetingswsdl.aspx
	_vti_bin/microsoft.sharepoint.dll
	_vti_bin/microsoft.sharepoint.portal.admin.search.dll
	_vti_bin/microsoft.sharepoint.portal.admin.search.xml
	_vti_bin/microsoft.sharepoint.portal.dll
	_vti_bin/microsoft.sharepoint.portal.singlesignon.dll
	_vti_bin/microsoft.sharepoint.portal.singlesignon.security.dll
	_vti_bin/microsoft.sharepoint.portal.singlesignon.xml
	_vti_bin/microsoft.sharepoint.portal.xml
	_vti_bin/microsoft.sharepoint.xml
	_vti_bin/officialfile.asmx
	_vti_bin/outlookadapter.asmx
	_vti_bin/outlookadapterdisco.aspx
	_vti_bin/outlookadapterwsdl.aspx
	_vti_bin/owssvr.dll
	_vti_bin/people.asmx
	_vti_bin/permissions.asmx
	_vti_bin/permissionsdisco.aspx
	_vti_bin/permissionswsdl.aspx
	_vti_bin/portalapi.aspx
	_vti_bin/publishedlinksservice.asmx
	_vti_bin/publishingservice.asmx
	_vti_bin/search.asmx
	_vti_bin/searchdisco.aspx
	_vti_bin/searchwsdl.aspx
	_vti_bin/sharepointemailws.asmx
	_vti_bin/shtml.dll
	_vti_bin/sitedata.asmx
	_vti_bin/sitedatadisco.aspx
	_vti_bin/sitedatawsdl.aspx
	_vti_bin/sites.asmx
	_vti_bin/sitesdisco.aspx
	_vti_bin/siteswsdl.aspx
	_vti_bin/slidelibrary.asmx
	_vti_bin/spdisco.aspx
	_vti_bin/spellcheck.asmx
	_vti_bin/spscrawl.asmx
	_vti_bin/spscrawldisco.aspx
	_vti_bin/spscrawlwsdl.aspx
	_vti_bin/spsdisco.aspx
	_vti_bin/spsearch.asmx
	_vti_bin/ssocli.dll
	_vti_bin/usergroup.asmx
	_vti_bin/usergroupdisco.aspx
	_vti_bin/usergroupwsdl.aspx
	_vti_bin/userprofilechangeservice.asmx
	_vti_bin/userprofileservice.asmx
	_vti_bin/userprofileservicedisco.aspx
	_vti_bin/userprofileservicewsdl.aspx
	_vti_bin/versions.asmx
	_vti_bin/versionsdisco.aspx
	_vti_bin/versionswsdl.aspx
	_vti_bin/views.asmx
	_vti_bin/viewsdisco.aspx
	_vti_bin/viewswsdl.aspx
	_vti_bin/web.config
	_vti_bin/webpartpages.asmx
	_vti_bin/webpartpagesdisco.aspx
	_vti_bin/webpartpageswsdl.aspx
	_vti_bin/webs.asmx
	_vti_bin/websdisco.aspx
	_vti_bin/webswsdl.aspx
	_vti_bin/workflow.asmx
	_vti_bin/wsdisco.aspx
	_vti_bin/wswsdl.aspx
	_vti_inf.html 
	_vti_pvt
	_wpresources
	accessdenied.aspx
	accessdeniedpage.aspx
	aclinv.aspx
	aclver.aspx
	addcontentsource.aspx
	addcontenttypetolist.aspx
	addfieldfromtemplate.aspx
	addfiletype.aspx
	addgrp1.aspx
	addgrp2.aspx
	addnavigationlinkdialog.aspx
	addrole.aspx
	addservernamemappings.aspx
	addwrkfl.aspx
	admin.dll
	adminrecyclebin.aspx
	advsetng.aspx
	alertdirectory.aspx
	alerts.asmx
	alertsadmin.aspx
	alertsdisco.aspx
	alertserror.aspx
	alertswsdl.aspx
	allgrps.aspx
	app_browsers
	app_globalresources
	applyregionalsettings.aspx
	approve.aspx
	areacachesettings.aspx
	areanavigationsettings.aspx
	areaservice.asmx
	areaservicedisco.aspx
	areaservicewsdl.aspx
	areatemplatesettings.aspx
	areawelcomepage.aspx
	aspnet_client
	aspxform.aspx
	assetedithyperlink.aspx
	assetimagepicker.aspx
	assetportalbrowser.aspx
	assetuploader.aspx
	associatedgroups.aspx
	associateportal.aspx
	assocwrkfl.aspx
	audience_chooser.aspx
	audience_chooser2.aspx
	audience_defruleedit.aspx
	audience_edit.aspx
	audience_list.aspx
	audience_main.aspx
	audience_memberlist.aspx
	audience_sched.aspx
	audience_view.aspx
	auditsettings.aspx
	authenticate.aspx
	author.dll
	autocat.aspx
	avreport.aspx
	avreport.htm
	backlinks.aspx
	barcodeimagefromitem.aspx
	bdcadminui/addbdcaction.aspx
	bdcadminui/addbdcapplication.aspx
	bdcadminui/addbdcapplication.aspx  
	bdcadminui/bdcapplications.aspx    
	bdcadminui/bdcentities.aspx           
	bdcadminui/editbdcaction.aspx         
	bdcadminui/exportbdcapplication.aspx  
	bdcadminui/managepermissions.aspx
	bdcadminui/viewbdcapplication.aspx
	bdcadminui/viewbdcentity.aspx
	bestbet.aspx
	bin
	bpcf.aspx
	bulkwrktaskhandler.aspx
	bulkwrktaskip.aspx
	businessdatasynchronizer.aspx
	category.aspx
	categorypickerpopup.aspx
	catman.aspx
	catpp1.aspx
	centraldatabaselock.aspx
	changecontenttypeoptionalsettings.aspx
	changecontenttypeorder.aspx
	changefieldorder.aspx
	changesitemasterpage.aspx
	checkin.aspx
	choosecs.aspx
	cmsslwpaddeditgroup.aspx
	cmsslwpaddeditlink.aspx
	cmsslwpeditview.aspx
	cmsslwpsortlinks.aspx
	confirmadvancedmode.aspx
	confirmalert.aspx
	confirmation.aspx
	conngps.aspx
	containerpicker.aspx
	contentaccessaccount.aspx
	contenttypeconvertersettings.aspx
	convertersettings.aspx
	copy.aspx
	copyresults.aspx
	copyrole.aspx
	copyutil.aspx
	crawledproperty.aspx
	create.aspx
	createadaccount.aspx
	createmysite.aspx
	createpage.aspx
	createwebpage.aspx
	createworkbook.aspx
	createws.aspx
	cspp1.aspx
	cspp2.aspx
	cstwrkflip.aspx
	ctdmsettings.aspx
	ctypedit.aspx
	ctypenew.aspx
	customizereport.aspx
	deactivatefeature.aspx
	default.aspx
	deletemu.aspx
	deleteweb.aspx
	discbar.aspx
	displaymappings.aspx
	dladvopt.aspx
	dmplaceholder.aspx
	dmworkspacemgmt.aspx
	docs/_layouts/viewlsts.aspx
	docs/default.aspx
	docs/documents/forms/allitems.aspx
	docs/lists/announcements/allitems.aspx
	docs/lists/announcements/dispform.aspx
	docs/lists/tasks/allitems.aspx
	doctrans.aspx
	download.aspx
	dspsts.asmx
	dspstsdisco.aspx
	dspstswsdl.aspx
	dws.asmx
	dws.aspx
	dwsdisco.aspx
	dwswsdl.aspx
	dynamicimageprovider.aspx
	editalert.aspx
	editcontentsource.aspx
	editcopyinformation.aspx
	editcrawlrule.aspx
	editdisplaymapping.aspx
	editdsserver.aspx
	editgrp.aspx
	editnav.aspx
	editpolicy.aspx
	editprms.aspx
	editprofile.aspx
	editproperty.aspx
	editpropertynames.aspx
	editpropertynames2.aspx
	editrelevancesettings.aspx
	editrole.aspx
	editschedule.aspx
	editsearchschedule.aspx
	editsearchsettings.aspx
	editsection.aspx
	editview.aspx
	emaildetails.aspx
	emailsettings.aspx
	enablealerts.aspx
	enhancedsearch.aspx
	error.aspx
	error.htm
	ewrcustomfilter.aspx
	ewrfilter.aspx
	ewrfind.aspx
	ewrpredialog.aspx
	ewrtop10.aspx
	excelcellpicker.aspx
	excelprofilepage.aspx
	excelrenderer.aspx
	excelserversafedataprovider.aspx
	excelserversafedataproviders.aspx
	excelserversettings.aspx
	excelservertrusteddcl.aspx
	excelservertrusteddcls.aspx
	excelservertrustedlocation.aspx
	excelservertrustedlocations.aspx
	excelserveruserdefinedfunction.aspx
	excelserveruserdefinedfunctions.aspx
	exemptpolicy.aspx
	exportpolicy.aspx
	exportwp.aspx
	expurlwp.aspx
	farmtopologyview.aspx
	feed.aspx
	filedlg.htm
	filetypes.aspx
	filter.aspx
	filtervaluespickerdialog.aspx
	fldedit.aspx
	fldeditex.aspx
	fldnew.aspx
	fldnewex.aspx
	fldpick.aspx
	folders.aspx
	fontdlg.htm
	formedt.aspx
	formresource.aspx
	forms.asmx
	forms/forms/allitems.aspx
	forms/myitems.aspx
	forms/newform.aspx
	formsdisco.aspx
	formserver.aspx
	formserverattachments.aspx
	formserverdetector.aspx
	formswsdl.aspx
	gear.aspx
	genericpicker.aspx
	getdataconnectionfile.aspx
	getssploginfo.aspx
	getsspscopes.aspx
	getsspstatus.aspx
	global.asax
	groups.aspx
	grpman.aspx
	grpmbrs.aspx
	grpsel.aspx
	help
	help.aspx
	helpcontent.aspx
	helpsearch.aspx
	hierarchyman.ascx
	hold.aspx
	holdreport.aspx
	htmledit.aspx
	htmltranslate.aspx
	htmltrredir.aspx
	htmltrverify.aspx
	iframe.aspx
	iframe.htm
	images/
	imaging.asmx
	imagingdisco.aspx
	imagingwsdl.aspx
	importdata.aspx
	importpolicy.aspx
	indxcol.aspx
	infopage.aspx
	iniwrkflip.aspx
	instable.htm
	irm.aspx
	irmrept.aspx
	itemrwfassoc.aspx
	iviewhost.aspx
	keyword.aspx
	keywordbbman.aspx
	labelimage.aspx
	linkschecker.aspx
	linkscheckerwiz.aspx
	listcontentsources.aspx
	listedit.aspx
	listenabletargeting.aspx
	listfeed.aspx
	listgeneralsettings.aspx
	listindexes.aspx
	listkeywords.aspx
	lists.asmx
	listsdisco.aspx
	listsearchschedules.aspx
	listsearchscopes.aspx
	listservernamemappings.aspx
	listswsdl.aspx
	listsyndication.aspx
	login.aspx
	logsummary.aspx
	logviewer.aspx
	longrunningoperationprogress.aspx
	lroperationstatus.aspx
	lstman.aspx
	lstman2.aspx
	lstsetng.aspx
	managecheckedoutfiles.aspx
	managecontenttype.aspx
	managecontenttypefield.aspx
	managecopies.aspx
	managecrawlrules.aspx
	managedproperty.aspx
	managefeatures.aspx
	managefeatures.aspx?scope=site
	managefiletypes.aspx
	manageitemscheduling.aspx
	manageprivacypolicy.aspx
	manageservicepermissions.aspx
	mapproperty.aspx
	matchingrule.aspx
	mcontent.aspx
	meetings.asmx
	meetingsdisco.aspx
	meetingswsdl.aspx
	menu.htc
	menubar.htc
	metaweblog.aspx
	mgrdsserver.aspx
	mgrproperty.aspx
	microsoft.sharepoint.dll
	microsoft.sharepoint.portal.admin.search.dll
	microsoft.sharepoint.portal.admin.search.xml
	microsoft.sharepoint.portal.dll
	microsoft.sharepoint.portal.singlesignon.dll
	microsoft.sharepoint.portal.singlesignon.security.dll
	microsoft.sharepoint.portal.singlesignon.xml
	microsoft.sharepoint.portal.xml
	microsoft.sharepoint.xml
	mngctype.aspx
	mngdisc.aspx
	mngfield.aspx
	mngsiteadmin.aspx
	mngsubwebs.aspx
	mngsubwebs.aspx?view=sites
	mobile/bloghome.aspx          
	mobile/default.aspx           
	mobile/delete.aspx            
	mobile/dispform.aspx  
	mobile/disppost.aspx  
	mobile/editform.aspx  
	mobile/mblerror.aspx  
	mobile/mbllists.aspx    
	mobile/mbllogin.aspx    
	mobile/mbllogout.aspx   
	mobile/mobileformserver.aspx  
	mobile/newcomment.aspx  
	mobile/newform.aspx
	mobile/newpost.aspx
	mobile/view.aspx
	mobile/viewcomment.aspx
	modwrkflip.aspx
	mtgredir.aspx
	myalerts.aspx
	mycontactlinks.aspx
	mygrps.aspx
	myinfo.aspx
	mymemberships.aspx
	mypage.aspx
	myquicklinks.aspx
	mysite.aspx
	mysite/_layouts/mysite.aspx
	mysite/person.aspx
	mysiteheader.aspx
	mysubs.aspx
	mytasks.aspx
	navoptions.aspx
	new.aspx
	newalert.aspx
	newalertfromsts.aspx
	newcatalog.aspx
	newdisplaymapping.aspx
	newdwp.aspx
	newfiletype.aspx
	newgrp.aspx
	newlink.aspx
	newmws.aspx
	newnav.aspx
	newpagelayout.aspx
	news/_layouts/viewlsts.aspx
	news/pages/default.aspx
	news/pages/newsarchive.aspx
	newsbweb.aspx
	newsiterule.aspx
	newtranslationmanagement.aspx
	newvariationsite.aspx
	nocrawlsettings.aspx
	notesedit.aspx
	noteswizard1.aspx
	noteswizard2.aspx
	noteswizard3.aspx
	noteswizard4.aspx
	objectcachesettings.aspx
	officialfilesetup.aspx
	officialfilesuccess.aspx
	osssearchresults.aspx
	outlookadapter.asmx
	outlookadapterdisco.aspx
	outlookadapterwsdl.aspx
	owners.aspx
	owssvr.dll
	pages/default.aspx
	pages/forms/allitems.aspx
	pages/forms/combine.aspx
	pages/forms/dispform.aspx
	pages/forms/editform.aspx
	pages/forms/webfldr.aspx 
	pagesettings.aspx
	pageversioninfo.aspx
	password.aspx
	permissions.asmx
	permissionsdisco.aspx
	permissionswsdl.aspx
	permsetup.aspx
	personalsites.aspx
	picker.aspx
	pickercontainer.aspx
	pickerresult.aspx
	pickertreeview.aspx
	policy.aspx
	policyconfig.aspx
	policycts.aspx
	policylist.aspx
	portal.aspx
	portalapi.aspx
	portalcreatesuccess.aspx
	portalheader.aspx
	portallist.aspx
	portalproperties.aspx
	portalsettings.aspx
	portalview.aspx
	postback.formserver.aspx
	print.formserver.aspx
	printloader.formserver.aspx
	prjsetng.aspx
	profadminedit.aspx
	profileredirect.aspx
	profmain.aspx
	profmngr.aspx
	profnew.aspx
	progresspage.aspx
	properties.aspx
	propertyproperties.aspx
	proxy.aspx
	publishback.aspx
	qlreord.aspx
	qstedit.aspx
	qstnew.aspx
	quicklinks.aspx
	quicklinksdialog.aspx
	quicklinksdialog2.aspx
	quicklinksdialogform.aspx
	quiklnch.aspx
	rcxform.aspx
	recyclebin.aspx
	redirect.aspx
	redirectpage.aspx
	redirectpage.aspx?target={sitecollectionurl}_catalogs/masterpage
	reghost.aspx
	regionalsetng.aspx
	releasehold.aspx
	rellinksscopesettings.aspx
	remwrkfl.aspx
	renderudc.aspx
	reorder.aspx
	report.aspx
	reporthome.aspx
	reporting.aspx
	reports/pages/default.aspx
	reqacc.aspx
	reqfeatures.aspx
	reqgroup.aspx
	reqgroupconfirm.aspx
	resolverecipient.aspx
	reusabletextpicker.aspx
	rfcxform.aspx
	rfpxform.aspx
	role.aspx
	rssxslt.aspx
	rte2ecell.aspx
	rte2erowcolsize.aspx
	rte2etable.aspx
	rte2pueditor.aspx
	rtedialog.aspx
	runreport.aspx
	savetmpl.aspx
	schema.aspx
	scope.aspx
	scopedisplaygroup.aspx
	scsignup.aspx
	search.asmx
	searchandaddtohold.aspx
	searchcenter/_layouts/viewlsts.aspx
	searchcenter/pages/default.aspx
	searchdisco.aspx
	searchreset.aspx
	searchresultremoval.aspx
	searchresults.aspx
	searchscope.aspx
	searchsettings.aspx
	searchsspsettings.aspx
	searchwsdl.aspx
	selcolor.htm
	selectcrawledproperty.aspx
	selectmanagedproperty.aspx
	selectpicture.aspx
	selectpicture2.aspx
	selectuser.aspx
	sendtoofficialfile.aspx
	setanon.aspx
	setimport.aspx
	setrqacc.aspx
	settings.aspx
	shared documents/forms/allitems.aspx
	shropt.aspx
	shtml.dll
	signature.formserver.aspx
	signaturedetails.formserver.aspx
	signaturedetailsloader.formserver.aspx
	signaturedetailspngloader.formserver.aspx
	signatureeula.formserver.aspx
	signout.aspx
	sitecachesettings.aspx
	sitedata.asmx
	sitedatadisco.aspx
	sitedatawsdl.aspx
	sitedirectory/_layouts/viewlsts.aspx
	sitedirectory/pages/category.aspx
	sitedirectory/pages/sitemap.aspx
	sitedirectorysettings.aspx
	sitelist.aspx
	sitemanager.aspx
	sitemanager.aspx?lro=all
	siteoperationrefuse.aspx
	sitepp1.aspx
	siterss.aspx
	sites.asmx
	sitesdisco.aspx
	sitesubs.aspx
	siteswsdl.aspx
	siteusrs.aspx
	sledit.aspx
	slnew.aspx
	smtcommentsdialog.aspx
	spaddrole.aspx
	spanon.aspx
	spcataddperm.aspx
	spcateditperm.aspx
	spcatsec.aspx
	spcf.aspx
	spcontnt.aspx
	spdisco.aspx
	speditcategory.aspx
	speditgroup.aspx
	speditlisting.aspx
	spellchecker.aspx
	spmovelisting.aspx
	spnewcategory.aspx
	spnewdashboard.aspx
	spnewgroup.aspx
	spnewlisting.aspx
	sps
	sps/default.aspx
	sps/farmtopologyview.aspx
	sps/portalcreatesuccess.aspx
	sps/portallist.aspx
	spsaclinv.aspx
	spscrawl.asmx
	spscrawldisco.aspx
	spscrawlwsdl.aspx
	spscreate.aspx
	spsredirect.aspx
	spsviewlsts.aspx
	spsviewtype.aspx
	spthemes.xml
	spthemes.xsd
	spusageconfig.aspx
	spusagesite.aspx
	spusagesiteclickthroughs.aspx
	spusagesitehomepage.aspx
	spusagesitereferrers.aspx
	spusagesitesearchqueries.aspx
	spusagesitesearchresults.aspx
	spusagesitetoppages.aspx
	spusagesiteusers.aspx
	spusagesspsearchqueries.aspx
	spusagesspsearchresults.aspx
	spusageweb.aspx
	spusagewebclickthroughs.aspx
	spusagewebhomepage.aspx
	spusagewebreferrers.aspx
	spusagewebtoppages.aspx
	spusagewebusers.aspx
	srchrss.aspx
	srchvis.aspx
	srman.aspx
	ssocli.dll
	ssologon.aspx
	storman.aspx
	stswebtemp.gif
	subchoos.aspx
	subedit.aspx
	submitrepair.aspx
	subnew.aspx
	success.aspx
	survedit.aspx
	templatepick.aspx
	themeweb.aspx
	tnreord.aspx
	toolpane.aspx
	topnav.aspx
	translatablesettings.aspx
	unapprovedresources.aspx
	updatecopies.aspx
	updateschedule.aspx
	upload.aspx
	urltranslate.aspx
	usage.aspx
	usagedetails.aspx
	useconfirmation.aspx
	user.aspx
	usergroup.asmx
	usergroupdisco.aspx
	usergroupwsdl.aspx
	userinfo.aspx
	userpicker.aspx
	userprofileservice.asmx
	userprofileservicedisco.aspx
	userprofileservicewsdl.aspx
	variationexport.aspx
	variationlabel.aspx
	variationlabels.aspx
	variationlogs.aspx
	variations/variationimport.aspx
	variationsettings.aspx
	versiondiff.aspx
	versions.asmx
	versions.aspx
	versionsdisco.aspx
	versionswsdl.aspx
	viewedit.aspx
	viewgrouppermissions.aspx
	viewlsts.aspx
	viewnew.aspx
	views.asmx
	viewscopes.aspx
	viewscopesettings.aspx
	viewsdisco.aspx
	viewseclsts.aspx
	viewswsdl.aspx
	viewtype.aspx
	vslist.aspx
	vssettings.aspx
	vsubwebs.aspx
	web.config
	webadmin.aspx
	webdeleted.aspx
	webpartgallerypickerpage.aspx
	webpartpages.asmx
	webpartpagesdisco.aspx
	webpartpageswsdl.aspx
	webperm.aspx
	webs.asmx
	websdisco.aspx
	webswsdl.aspx
	webusers.aspx
	wfelist.aspx
	workflow.aspx
	workspce.aspx
	wpeula.aspx
	wpresources
	wrkmng.aspx
	wrksetng.aspx
	wrkstat.aspx
	wrktaskip.aspx
	wsdisco.aspx
	wsrpmarkupproxy.aspx
	wswsdl.aspx
	xlatewfassoc.aspx
	xlviewer.aspx
	zoombldr.aspx"""


def listSub():
	return """_layouts/userdisp.aspx?id
	_layouts/useredit.aspx?source=%2f%5flayouts%2fpeople%2easpx&id
	_layouts/people.aspx?membershipgroupid
	_layouts/wpprevw.aspx?id
	forms/dispform.aspx?id
	forms/editform.aspx?id
	people.aspx?membershipgroupid
	userdisp.aspx?id
	useredit.aspx?source=%2f%5flayouts%2fpeople%2easpx&id
	wpprevw.aspx?id	"""